# Change these first
owner: sukanyeah
repo: uptime

sites:
  - name: Sukanyeah.com
    url: https://www.sukanyeah.com
  - name: 1Account.org
    url: https://www.1account.org
  - name: Sukanyeah Blog
    url: https://ml.sukanyeah.com
  - name: Sukanyeah No Hello
    url: https://nohello.sukanyeah.com
  - name: Sukanyeah.in
    url: https://www.sukanyeah.in
  - name: Syah.in
    url: https://www.syah.in
  - name: Sukanyeah Solar
    url: https://solar.sukanyeah.com
  - name: Short URL System
    url: https://go.syah.in
  - name: Short URL System (SK)
    url: https://go.sukanyeah.com

status-website:
  cname: status.sukanyeah.com
  logoUrl: https://img.syah.in/mSlUdQrdFuKV4JOz/logos/sukanyeah_fly.svg
  name: Sukanyeah
  introTitle: "**Sukanyeah** Uptime Status."
  introMessage:
  navbar:
    - title: Blog
      href: https://ml.sukanyeah.com/
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
