# Change these first
owner: Sukanyeah # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Sukanyeah.com
    url: https://www.sukanyeah.com
  - name: Sukanyeah.in
    url: https://www.sukanyeah.in
  - name: Syah.in
    url: https://www.syah.in
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sukanyeah.com
  # baseUrl: /your-repo-name
  logoUrl: https://d15a02u2vz5xwk.cloudfront.net/mSlUdQrdFuKV4JOz/logos/sukanyeah_fly.svg
  name: Sukanyeah
  introTitle: "**Sukanyeah** Uptime Status."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
